config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :responses, only: [:create, :index]
  resources :clues
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'

  get  '/about',   to: 'static_pages#about'

  get  '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'

  post '/signup',  to: 'users#create'

  post '/join_team',    to: 'users#join_team'  

  get  '/login',   to: 'sessions#new'

  post '/login',   to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only:[:new, :create, :edit, :update]

  resources :microposts,  only: [:create, :destroy]

  resources :teams, only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  

  def home

    if logged_in?

      @micropost  = current_user.microposts.build

      @feed_items = current_user.feed.paginate(page: params[:page])

    end

  end

  def help
  end

  def about
  end

  def contact
  end
  

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h2>here's some junk in an h2</h2>
<p>
  and some more stuff in a paragraph
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>

<p>

  Contact the Ruby on Rails Tutorial about the sample app at the

  <a href="http://www.railstutorial.org/contact">contact page</a>.

</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>


<h1>Help</h1>

<p>

  Get help on the Ruby on Rails Tutorial at the

  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.

  To get help on this sample app, see the

  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>

  book</a>.

</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
	<div class="jumbotron jumbotron-fluid">
	<div class="container text-center">
		<h3>Race 615 - East Nashville Edition</h3>
	  <p>Sat Oct 28th - 1:00 PM</p>
		<%= link_to "See who's registred", users_path, class: "btn btn-lg btn-primary" %>
	</div>
</div>


<% else %>


<div class="jumbotron jumbotron-fluid">
	<div class="container text-center">
		<h3>Race 615 - East Nashville Edition</h3>
	  <p>Sat Oct 28th - 1:00 PM</p>
		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
</div>

<% end %>


<div class="container">
	<h1>How it Works</h1>
	<p class="lead">
		RACE615 is an Amazing Race style event. Amazing Race is a (really good!) reality TV show where teams of 2 compete in a race around the world. Teams are given clues that take them to different locations, and they must complete physical/mental challenges along the way. 

We are going to keep it local, so all travel will be on foot-- and occasionally by Uber or bike--  around East Nashville. This round, we will be sticking specifically to <b class="font-weight-bold">East Nashville.</b> You should expect the race to take about 3 hours and you will be walking/jogging about 3.5-4 miles in total. There will be mental challenges that will test your problem solving abilities, physical challenges that will test your strength as a team, and mandatory food/beverage breaks along the way. We have created this event with our friends and family in mind, so nothing is going to be unpleasant- only fun!
	</p>
	<h3>What you need to know</h3>
	<ol>
		<li>
			Race615 will begin at <%= link_to "East Park", "https://www.google.com/maps/place/East+Park/@36.1810602,-86.773038,13z/data=!4m8!1m2!2m1!1seast+park!3m4!1s0x886467cd4c03e405:0xc8d0f6aa50fea8ca!8m2!3d36.1729263!4d-86.7602371", target: :_blank %> on <b class="font-weight-bold">Saturday, September 28 at 1:00PM.</b> Come early to get ready and size up the competition : )
		</li>
		<li>
			Parking around East Park on the street is free. Cabbing/Lyfting/carpooling to the park is also always an option!
		</li>
		<li>
			You will be interacting with a <b>this web app</b> in order to receive clues and submit responses, so you will need to have internet access on your phones. (We suggest that your team have 2 fully charged cell phones)
		</li>
		<li>
			Use your resources! Clues are difficult/obscure, so Google searching or asking locals is encouraged!
		</li>
		<li>
			All travel will be on foot unless otherwise specified. You will walk/ jog about 4 miles.
		</li>
		<li>
			<b>You will need to bring:</b> 1 pen/pencil, 2 fully charged cell phones, and 1 individually wrapped small snack per teammate (ex: snickers bar, crackers, bag of chips)... if you need a way to carry these things, <%= link_to "fanny packs are awesome!", "https://www.bonanza.com/booths/Bam_Products?item_sort_options[filter_string]=Neon+Fanny+Pack", target: :_blank %>
		</li>
		<li>
			Team costumes/ outfits are encouraged. It is Halloween weekend, afterall!
		</li>
	</ol>
	<h3>How to participate</h3>
	<ol>
		<li> Register on the site by clicking the sign up button</li>
		<li> Have your teammate register on the site as well</li>
		<li> Create a team on the site (coming soon!)</li>
		<li> Have your teammate join your team (teams of 2 required)</li>
		<li> Show up on Saturday ready to have fun :)</li>
	</ol>

	<p>
		YAY! We are SO EXCITED to be putting this event on for all of you, so please let us know if you have any further questions. 

See you on the race course : )
-The WarDorrs
	</p>

 
</div>