config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :responses, only: [:create, :index]
  resources :clues
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'

  get  '/about',   to: 'static_pages#about'

  get  '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'

  post '/signup',  to: 'users#create'

  post '/join_team',    to: 'users#join_team'  

  get  '/login',   to: 'sessions#new'

  post '/login',   to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only:[:new, :create, :edit, :update]

  resources :microposts,  only: [:create, :destroy]

  resources :teams, only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <p>
          Any questions can be sent to <a href="mailto:ryandorr17@gmail.com?subject=race questions">ryan</a> or <a href="mailto:beth.w.dorr@gmail.com?subject=race questions">beth</a>
        </p>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

  <div class="container">

    <%= link_to "race615", root_path, id: "logo" %>
    <nav>

      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %></li>

        <!-- <li>add about here</li> -->


        <% if logged_in? %>

        <li><%= link_to "Competitors", users_path %></li>

        <li><%= link_to "Race!", current_user %></li>


        <% if current_user.admin? %>
          <li><%= link_to "Clues", clues_path %></li>
          <li><%= link_to "Books", books_path %></li>
        <% end %>


        <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              Account <b class="caret"></b>

            </a>

            <ul class="dropdown-menu">

              <li><%= link_to "Profile", current_user %></li>

              <li><%= link_to "Settings", edit_user_path(current_user) %></li>

              <li class="divider"></li>

              <li>

                <%= link_to "Log out", logout_path, method: "delete" %>

              </li>

            </ul>

          </li>

        <% else %>


        <li><%= link_to "Log in", login_path %></li>

        <% end %>

      </ul>

    </nav>

  </div>

</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>

  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">

  </script>

<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">

      <% flash.each do |message_type, message| %>

        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>

      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>

    </div>



  </body>


</html>