config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :responses, only: [:create, :index]
  resources :clues
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'

  get  '/about',   to: 'static_pages#about'

  get  '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'

  post '/signup',  to: 'users#create'

  post '/join_team',    to: 'users#join_team'  

  get  '/login',   to: 'sessions#new'

  post '/login',   to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only:[:new, :create, :edit, :update]

  resources :microposts,  only: [:create, :destroy]

  resources :teams, only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/clue.rb
class Clue < ApplicationRecord
mount_uploader :picture, PictureUploader 
  validate :picture_size


  private

  def picture_size

      if picture.size > 5.megabytes

        errors.add(:picture, "should be less than 5MB")

      end

   end 






end

app/controllers/clues_controller.rb
class CluesController < ApplicationController
  before_action :set_clue, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :admin_user

  # GET /clues
  # GET /clues.json
  def index
    @clues = Clue.all
  end

  # GET /clues/1
  # GET /clues/1.json
  def show
  end

  # GET /clues/new
  def new
    @clue = Clue.new
  end

  # GET /clues/1/edit
  def edit
  end

  # POST /clues
  # POST /clues.json
  def create
    @clue = Clue.new(clue_params)

    respond_to do |format|
      if @clue.save
        format.html { redirect_to @clue, notice: 'Clue was successfully created.' }
        format.json { render :show, status: :created, location: @clue }
      else
        format.html { render :new }
        format.json { render json: @clue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clues/1
  # PATCH/PUT /clues/1.json
  def update
    respond_to do |format|
      if @clue.update(clue_params)
        format.html { redirect_to @clue, notice: 'Clue was successfully updated.' }
        format.json { render :show, status: :ok, location: @clue }
      else
        format.html { render :edit }
        format.json { render json: @clue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clues/1
  # DELETE /clues/1.json
  def destroy
    @clue.destroy
    respond_to do |format|
      format.html { redirect_to clues_url, notice: 'Clue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clue
      @clue = Clue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clue_params
      params.require(:clue).permit(:stop, :location, :clue, :activity, :answer, :picture)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
end

app/helpers/clues_helper.rb
module CluesHelper
end

app/views/clues/_form.html.erb
<%= form_with(model: clue, local: true) do |form| %>
  <% if clue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clue.errors.count, "error") %> prohibited this clue from being saved:</h2>

      <ul>
      <% clue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stop %>
    <%= form.number_field :stop, id: :clue_stop %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :clue_location %>
  </div>

  <div class="field">
    <%= form.label :clue %>
    <%= form.text_area :clue, id: :clue_clue %>
  </div>

  <div class="field">
    <%= form.label :activity %>
    <%= form.text_field :activity, id: :clue_activity %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer, id: :clue_answer %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <span>
      <%= form.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clues/edit.html.erb
<h1>Editing Clue</h1>

<%= render 'form', clue: @clue %>

<%= link_to 'Show', @clue %> |
<%= link_to 'Back', clues_path %>

app/views/clues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clues</h1>

<table>
  <thead>
    <tr>
      <th>Stop</th>
      <th>Location</th>
      <th>Clue</th>
      <th>Activity</th>
      <th>Answer</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clues.each do |clue| %>
      <tr>
        <td><%= clue.stop %></td>
        <td><%= clue.location %></td>
        <td><%= clue.clue %></td>
        <td><%= clue.activity %></td>
        <td><%= clue.answer %></td>
        <td><%= clue.picture %></td>
        <td><%= link_to 'Show', clue %></td>
        <td><%= link_to 'Edit', edit_clue_path(clue) %></td>
        <td><%= link_to 'Destroy', clue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clue', new_clue_path %>

app/views/clues/new.html.erb
<h1>New Clue</h1>

<%= render 'form', clue: @clue %>

<%= link_to 'Back', clues_path %>

app/views/clues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stop:</strong>
  <%= @clue.stop %>
</p>

<p>
  <strong>Location:</strong>
  <%= @clue.location %>
</p>

<p>
  <strong>Clue:</strong>
  <%= @clue.clue %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @clue.activity %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @clue.answer %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @clue.picture %>
</p>

<%= link_to 'Edit', edit_clue_path(@clue) %> |
<%= link_to 'Back', clues_path %>